import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/ui/componentes/Header";
import Footer from "@/ui/componentes/Footer";
import { GlobalProvider } from "@/ui/context/GlobalContext";
import { GoogleTagManager } from "@next/third-parties/google";
import VLibrasFunction from "@/ui/componentes/VLibras";

const inter = Inter({ subsets: ["latin"] });
const gtmTag = process.env.GTM_TAG || "";

export const metadata: Metadata = {
    title: "Domba App",
    description: "Generated by UNIVESP students",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <GlobalProvider>
            <html lang="en">
                <GoogleTagManager gtmId={gtmTag} />
                <body
                    className={inter.className}
                    //style={{ backgroundColor: '#60a5fa', margin: 0 }} muda a cor do fundo
                >
                    {/* <Header /> */}
                    <VLibrasFunction />
                    {children}
                    {/* <Footer /> */}
                </body>
            </html>
        </GlobalProvider>
    );
}
